# Site settings
title: Koyo Blog
SEOTitle: 虎哥的博客 | Koyo Blog
header-img: img/home-bg.jpg
email: qzy922@gmail.com
description: "Cool Blog"
keyword: ""
#url: "http://huangxuan.me"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'
timezone: +0900
future: true


# SNS settings
RSS: false
weibo_username:     2045173904  # caution, non-VIP users maybe using number-ids
zhihu_username:     qian-wei-shuo
github_username:    koyo922
#twitter_username:  huxpro
facebook_username:  100005178853657


# Build settings
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
gems: [jekyll-paginate, jemoji]


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter: rouge
  default_lang: bash

# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: koyo922
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
#ba_track_id: b35c404edec0879e21940eda6ea698dc
ba_track_id: a2bb43ef451f25a0f65288a7a1189357
# Google Analytics
#ga_track_id: 'UA-73383919-1'
ga_track_id: 'UA-73383919-2'
#ga_domain: blog.koyo.xyz
ga_domain: koyo922.github.io

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
# sidebar-about-description: "写写代码，做做设计，看看产品。世界那么大，多玩玩看看。"
sidebar-about-description: "我要吃：麻辣香锅、重庆火锅、重庆小面、烤肉串、烤鱼、水煮鱼、兰州牛肉面、桂林米粉、炕土豆、东坡肉、炖腊蹄子、干煸四季豆、清炒荷兰豆……"
sidebar-avatar: /img/avatar-koyo.png      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me"
    },{
        title: "devtang",
        href: "http://blog.devtang.com/"
    },{
        title: "Bar",
        href: "#"
    },{
        title: "It helps SEO",
        href: "#"
    }
]

defaults:
    -
      scope:
          path: ""
          type: "posts"
      values:
          css: "koyo-markdown"
          author: "koyo"
          layout: "post"

